// Nomes amigáveis para campos e ações exibidos na auditoria.

export const FIELD_LABELS = {
  plate: 'Placa',
  fleet_number: 'Nº da frota',
  brand: 'Marca',
  model: 'Modelo',
  year_manufacture: 'Ano fabricação',
  year_model: 'Ano modelo',
  chassis: 'Chassi',
  renavam: 'RENAVAM',
  type: 'Tipo',
  fuel_type: 'Combustível',
  tank_capacity: 'Capacidade do tanque',
  current_km: 'Quilometragem',
  acquisition_date: 'Data de aquisição',
  status: 'Status',
  axle_config: 'Configuração de eixos',
  notes: 'Observações',
  full_name: 'Nome',
  cpf: 'CPF',
  cnh_number: 'Nº CNH',
  cnh_category: 'Categoria CNH',
  cnh_expiry: 'Validade CNH',
  phone: 'Telefone',
  admission_date: 'Admissão',
  username: 'Usuário',
  email: 'E-mail',
  job_title: 'Cargo',
  is_active: 'Ativo',
  must_change_password: 'Trocar senha no 1º acesso',
  permissoes: 'Permissões',
  motorista: 'Motorista',
  implemento: 'Implemento',
  arquivo: 'Arquivo',
  occurred_on: 'Data',
  description: 'Descrição',
  vehicle_id: 'Veículo',
  cnh_dias: 'Aviso CNH (dias)',
  documento_dias: 'Aviso documentos (dias)',
  manutencao_dias: 'Aviso manutenção (dias)',
  manutencao_km: 'Aviso manutenção (km)',
  oleo_km: 'Aviso troca de óleo (km)',
  km_salto_maximo: 'Salto máximo de KM',
  oleo_intervalo_km: 'Intervalo da troca de óleo (km)',
  nome: 'Nome da empresa',
  fueled_at: 'Data/hora',
  km: 'KM',
  station: 'Posto',
  city: 'Cidade',
  state: 'UF',
  liters: 'Litros',
  price_per_liter: 'Valor por litro',
  total: 'Valor total',
  full_tank: 'Tanque cheio',
  order_id: 'Ordem de abastecimento',
  order_ref: 'Nº ordem externa',
  driver_id: 'Motorista',
  order_date: 'Data da ordem',
  max_liters: 'Limite de litros',
  max_amount: 'Limite de valor',
  cnpj: 'CNPJ',
  categories: 'Categorias',
  performed_on: 'Data',
  workshop: 'Oficina',
  responsible: 'Responsável',
  parts_cost: 'Valor das peças',
  labor_cost: 'Mão de obra',
  invoice_number: 'Nota fiscal',
  next_date: 'Próxima (data)',
  next_km: 'Próxima (KM)',
  oil_brand: 'Marca do óleo',
  oil_type: 'Tipo do óleo',
  oil_spec: 'Especificação',
  oil_quantity: 'Qtd. de óleo',
  oil_filter: 'Filtro de óleo',
  fuel_filter: 'Filtro de combustível',
  air_filter: 'Filtro de ar',
  pecas: 'Peças',
  opened_on: 'Abertura',
  reported_problem: 'Problema relatado',
  services_done: 'Serviços realizados',
  due_date: 'Previsão',
};

export const ACTION_LABELS = {
  criar: 'Cadastro',
  editar: 'Edição',
  excluir: 'Exclusão',
  inativar: 'Inativação',
  alterar_status: 'Alteração de status',
  atualizar_km: 'Atualização de KM',
  correcao_km: 'Correção de KM',
  vincular_motorista: 'Vínculo de motorista',
  engatar: 'Engate',
  desengatar: 'Desengate',
  anexar: 'Anexo incluído',
  remover_anexo: 'Anexo removido',
  alterar_permissoes: 'Alteração de permissões',
  redefinir_senha: 'Senha redefinida',
  trocar_senha: 'Troca de senha',
  ativar: 'Ativação',
  desativar: 'Desativação',
  desbloquear: 'Desbloqueio',
  encerrar_sessoes: 'Sessões encerradas',
  registrar_ocorrencia: 'Ocorrência registrada',
  cancelar_ocorrencia: 'Ocorrência cancelada',
  exportar: 'Exportação',
  cancelar: 'Cancelamento',
  finalizar: 'Finalização',
  incluir_peca: 'Peça incluída',
  remover_peca: 'Peça removida',
};

export const ACCESS_EVENTS = {
  login_ok: 'Login',
  login_falha: 'Falha de login',
  login_bloqueado: 'Tentativa com usuário bloqueado',
  login_suspeito: 'Tentativa suspeita (IP)',
  logout: 'Saída',
  senha_alterada: 'Senha alterada',
  senha_falha: 'Senha atual incorreta',
};

export const ENTITY_LABELS = {
  veiculo: 'Veículo',
  vehicle: 'Veículo',
  motorista: 'Motorista',
  driver: 'Motorista',
  usuario: 'Usuário',
  configuracao: 'Configuração',
  auditoria: 'Auditoria',
  abastecimento: 'Abastecimento',
  fueling: 'Abastecimento',
  ordem_abastecimento: 'Ordem de abastecimento',
  fuel_order: 'Ordem de abastecimento',
  manutencao: 'Manutenção',
  maintenance: 'Manutenção',
  ordem_servico: 'Ordem de serviço',
  service_order: 'Ordem de serviço',
};
